import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./styles/index.scss";


import Cart from "@/app/(app)/providers/Cart";
import Header from "@/app/(app)/components/shared/header";

import {getPayloadHMR} from "@payloadcms/next/utilities";
import config from "@payload-config";
import type {MenuItem, ContactDatum} from "@/payload-types";

const natsRegular = localFont({
  src: './fonts/NATS-Regular.woff',
  variable: '--font-nats'
})
const kokoroRegular = localFont({
  src: './fonts/Kokoro-Regular.ttf',
  variable: '--font-kokoro'
})


export const metadata: Metadata = {
  title: "Echo Sphere",
  description: "Generated by create next app",
};

interface LayoutProps {
    children: React.ReactNode;
}

export default async function RootLayout({children}: LayoutProps) {
  return (
        <html lang="en">
          <body className={`${natsRegular.variable} ${kokoroRegular.variable} bg-gray-300`}>
            <Cart>
                <Header/>
                <main>
                <div className={"emptyRow"} style={{gridColumn: 1/-1, height: "100px"}}></div>
                  {children}
                </main>
            </Cart>
          {/*<footer>*/}
          {/*  <p>Footer</p>*/}
          {/*</footer>*/}
          </body>
        </html>
  );
}

