import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./styles/index.scss";

import {MenuProvider} from "@/app/(app)/hooks/MenuContext";

import Cart from "@/app/(app)/providers/Cart";
import Header from "@/app/(app)/components/shared/header";
import Logo from "@components/shared/logo";
import NavButtonContainer from "@components/shared/nav-button-container";
import SideCart from "@components/SideCart";

const natsRegular = localFont({
  src: './fonts/NATS-Regular.woff',
  variable: '--font-nats'
})
const kokoroRegular = localFont({
  src: './fonts/Kokoro-Regular.ttf',
  variable: '--font-kokoro'
})


export const metadata: Metadata = {
  title: "Echo Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en">
          <body className={`${natsRegular.variable} ${kokoroRegular.variable} bg-gray-300`}>
            <Cart>
                <Header>
                    <Logo/>
                    <NavButtonContainer/>
                    <SideCart/>
                </Header>
                <main>
                <div className={"emptyRow"} style={{gridColumn: 1/-1, height: "100px"}}></div>
                  {children}
                </main>
            </Cart>
          {/*<footer>*/}
          {/*  <p>Footer</p>*/}
          {/*</footer>*/}
          </body>
        </html>
  );
}
