import React from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "@globals/index.scss";

import Cart from "@/app/(app)/providers/Cart";
import Header from "@components/shared/header";

import {TransitionProvider} from "@providers/TransitionContext";
import TransitionBox from "@components/pageTransition/TransitionBox"
import TransitionHandler from "@components/pageTransition/TransitionHandler"

const natsRegular = localFont({
  src: '../fonts/NATS-Regular.woff',
  variable: '--font-nats'
})
const kokoroRegular = localFont({
  src: '../fonts/Kokoro-Regular.ttf',
  variable: '--font-kokoro'
})

export const metadata: Metadata = {
  title: "Echo Sphere",
  description: "Generated by create next app",
};

interface LayoutProps {
    children: React.ReactNode;
}

export default async function RootLayout({children}: LayoutProps) {
  return (
      <TransitionProvider>
        <html lang="en">
          <body className={`${natsRegular.variable} ${kokoroRegular.variable} bg-gray-300`}>
          <TransitionBox/>
          <TransitionHandler/>
          <Cart>
                {/*<AnimatePresence mode={"wait"} initial={"false"}>*/}
                    <Header/>
                     <main>
                         <div className={"emptyRow"} style={{gridColumn: 1/-1, height: "100px"}}></div>
                         {children}
                     </main>
                {/*</AnimatePresence>*/}
            </Cart>
          </body>
        </html>
      </TransitionProvider>
  );
}

